drop TABLE DS_STAGE;
CREATE TABLE DS_STAGE
(
   DRUG_CONCEPT_CODE        VARCHAR2(255 Byte),
   INGREDIENT_CONCEPT_CODE  VARCHAR2(255 Byte),
   
   AMOUNT_VALUE             FLOAT(126),
   AMOUNT_UNIT              VARCHAR2(255 Byte),
   NUMERATOR_VALUE          FLOAT(126),
   NUMERATOR_UNIT           VARCHAR2(255 Byte),
   DENOMINATOR_VALUE        FLOAT(126),
   DENOMINATOR_UNIT         VARCHAR2(255 Byte),
   BOX_SIZE                 INTEGER
);
drop  TABLE PACK_CONTENT;
CREATE TABLE PACK_CONTENT
(
   PACK_CONCEPT_CODE  VARCHAR2(255 Byte),
   DRUG_CONCEPT_CODE  VARCHAR2(255 Byte),
   AMOUNT             NUMBER,
   BOX_SIZE           NUMBER)
;
drop TABLE INTERNAL_RELATIONSHIP_STAGE;
CREATE TABLE INTERNAL_RELATIONSHIP_STAGE
(
   CONCEPT_CODE_1     VARCHAR2(50 Byte),
   CONCEPT_CODE_2     VARCHAR2(50 Byte)
);

drop TABLE RELATIONSHIP_TO_CONCEPT;
CREATE TABLE RELATIONSHIP_TO_CONCEPT
(
   CONCEPT_CODE_1     VARCHAR2(255 Byte),
   VOCABULARY_ID_1    VARCHAR2(20 Byte),
   CONCEPT_ID_2       INTEGER,
   PRECEDENCE         INTEGER,
   CONVERSION_FACTOR  FLOAT(126)
);
